package io.avaje.http.api;

import io.javalin.plugin.Plugin;

/**
 * A Javalin 6 route generated by avaje http javalin generator.
 */
public abstract class AvajeJavalinPlugin extends Plugin<Void> {

  protected AvajeJavalinPlugin() {}

}
