package io.avaje.http.api.javalin;

import io.javalin.plugin.Plugin;

/**
 * A Javalin 7 route generated by avaje http javalin generator.
 */
public abstract class AvajeJavalinPlugin extends Plugin<Void> {

  protected AvajeJavalinPlugin() {}

}
