package io.dinject.controller;

/**
 * Registers routes to a web framework.
 * <p/>
 * Implementations can be generated by APT processing adapting web route requests
 * to controller methods.
 */
public interface WebRoutes {

  /**
   * Register routes.
   */
  void registerRoutes();
}
