
name: JDK EA Stable

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '39 1 * * 1,3,5'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net
        release: ea
        version: stable
    - name: Maven cache
      uses: actions/cache@v4
      env:
        cache-name: maven-cache
      with:
        path:
          ~/.m2
        key: build-${{ env.cache-name }}
    - name: Maven version
      run: mvn --version
    - name: Build with Maven
      run: mvn clean verify package -Ptest
