/** Generate the prisms to access annotation info */
@GeneratePrism(value = io.avaje.http.api.Controller.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.BeanParam.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.QueryParam.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Client.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Cookie.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Default.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Delete.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Form.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.FormParam.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Get.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Header.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.MatrixParam.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Patch.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Path.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Post.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Produces.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Put.class, publicAccess = true)
@GeneratePrism(value = jakarta.inject.Inject.class)
@GeneratePrism(value = io.swagger.v3.oas.annotations.OpenAPIDefinition.class, publicAccess = true)
@GeneratePrism(value = io.swagger.v3.oas.annotations.tags.Tag.class, publicAccess = true)
@GeneratePrism(value = io.swagger.v3.oas.annotations.tags.Tags.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.OpenAPIResponse.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.OpenAPIResponses.class, publicAccess = true)
@GeneratePrism(value = io.swagger.v3.oas.annotations.Hidden.class, publicAccess = true)
@GeneratePrism(value = javax.validation.Valid.class, name = "JavaxValidPrism", publicAccess = true)
@GeneratePrism(value = jakarta.validation.Valid.class, publicAccess = true)
@GeneratePrism(value = org.jetbrains.annotations.NotNull.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Client.class, publicAccess = true)
@GeneratePrism(value = io.avaje.http.api.Client.Import.class, publicAccess = true)
package io.avaje.http.generator.core;

import io.avaje.prism.GeneratePrism;
